### PR TITLE
Alternative I made for the badges(with colors)+ little change

### PR DESCRIPTION
**Pull request by frju365**

### CODE REVIEW

**Review by scith — APPROVED** [review]

**Comment by scith** [comment]
After second thoughts, I'm wondering if this is really necessary, given that the page already displays a message if the app is community.
The purpose of the badge being perhaps more of a "clickbait", wouldn't it be better if simpler ? :D 
Just a thought

**Comment by frju365** [comment]
It was for the style, not really to give an information about the level of the package. And it's just an alternative. It's for the website which promote Yunohost package. = saying it's official on a website does a better effect, than a neutral badge : it's my point. Even if it's community, it's better to have a badge with colors.
Moreover, I don't want to discuss on this, if you don't need them, so close the PR. But that doesn't prevent me to use them as well. It was, in fact, just to share my work(little) and to add a choice.

**Comment by scith** [comment]
Sure, then I'm OK with this. Let's try to speed up the merge:
- Minor decision
- Ends May 17
- Need one more review to merge in advance: @M5oul ?

**Comment by scith** [comment]
Sure, then I'm OK with this. Let's try to speed up the merge:
- Minor decision
- Ends May 17
- Need 2 reviews from the Com group? @M5oul @zamentur @opi @Jibec @Psycojoker @theodorefaure ?

**Comment by Jibec** [comment]
Thanks for this work!

I understand the aim to tell whether the app is community or official. But I'm unsure if we really should do it.

I understand the core team is adding the possibility to add more application list in interface. I assume it means there may me more list in the future.
It may also be hard to maintain if there is no webservice providing automatically the appropriate badge.

**Comment by maniackcrudelis** [comment]
It's really something lacking today. It's sometimes hard to know if an app is official or community.
Is there a way to link that to the web service ? To let it give us the good picture whether the app is official or community ?

**Review by maniackcrudelis — APPROVED** [review]

**Comment by frju365** [comment]
I think it possible to link that to the web service with the badges system. This PR is very old...  You are a bit late...

**Comment by Psycojoker** [comment]
Hello,

I found the bottom text really hard to read :x (at first I didn't even noticed that it was there) and I find it weird to use "red" for "official", shouldn't it be "green" or something like that? In classical color convention red is "danger" and "green" is "success" or "approved/positive".

Otherwise I like the intent of this PR :)

**Comment by frju365** [comment]
Well, when we oppose Blue and Red, Red is the most important in style convention and you see it better. I agree I have to make better size for the font, but it's to not have a big badge. I can change color, but from my point of view it was better to have the opposition between Red (flashy color) and blue.

**Comment by zamentur** [comment]
> when we oppose Blue and Red

In this situation blue and red are not opposed as there is only one of this color on the page when the user see it.

I completely agree with Bram, red is danger.

I agree with Bram text should be bigger, if we can't make it bigger, i really ask me if it's a good idea to put different images. I mean this image is made to be put on external website, page of apps... The important info is: "yunohost exists" and "a ynh package exist for this app". 

If there is place for a second indication, it could be also ; package is at least level 3/working or not. 

Except if we decide to keep only one simple image as today, the image should be dynamically chosen, if we ask an upstream for adding the community image/link and next ask for adding the official one, it will add some work for them. Probably in some situation it will not be done.

**Comment by frju365** [comment]
That was a bad idea to open this PR :/

**Pull request closed without merging**
